name: CI

on:
    push:

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 10
            matrix:
                php: ['7.2', '7.3', '7.4', '8.0']

        steps:
            - name: Set up PHP
              uses: shivammathur/setup-php@2.7.0
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download dependencies
              run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

            - name: Run tests
              run: ./vendor/bin/phpunit

            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v1.1.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
