name: Static analysis

on:
    pull_request: ~
    push:
        branches:
            - main

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:2.18.1
              with:
                 args: --dry-run --diff-format udiff
